import 'package:flutter/material.dart';

Image getImageIcon(String name, {double? size}) {
  return Image.asset(
    "assets/icons/$name-96.png",
    height: size ?? 50,
    width: size ?? 50,
    errorBuilder: (context, error, stackTrace) {
      return Image.asset(
        "assets/icons/unavailable-96.png",
        height: size ?? 50,
        width: size ?? 50,
      );
    },
  );
}

List<String> getAllIconNames() {
  return [
    "",
    "chest",
    "bodybuilder",
    "biceps",
    "calves",
    "hamstrings",
    "leg",
    "middle-back",
    "muscle",
    "posture",
    "prelum",
    "quadriceps",
    "shoulders",
    "trapezius",
    "triceps",
    "bench-press",
    "bouldering",
    "curls-with-dumbbells",
    "deadlift-skin-type-2",
    "exercise",
    "floating-guru-skin-type-2",
    "gymnastics",
    "judo-skin-type-2",
    "pushups",
    "roller-skating",
    "rowing-machine",
    "sit-ups",
    "skipping-rope",
    "squats",
    "staircase",
    "stepper",
    "swimming",
    "taekwondo",
    "treadmill",
    "trekking",
    "weightlifting",
    "workout",
    "swim",
    "battle-ropes",
    "balance",
    "bmi",
    "staircase-skin-type-2",
    "stretching-hamstring",
    "racquetball",
    "hockey",
    "fitness-skin-type-2",
    "person-lying-down",
    "pilates",
    "broken-leg",
    "boxing-glove",
    "muscle-flexing",
    "cycling-skin-type-2",
    "dragon-boat",
    "strength",
    "basketball-net",
    "barbells",
    "lungs",
  ];
}
