name: Ensure Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  flutter-android-build:
    name: Build APK (debug)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Flutter Pub packages
        uses: actions/cache@v3
        with:
          path: ${{ env.HOME }}/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle','**/*.gradle.kts','android/gradle.properties') }}

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          
      - name: Enable Flutter analytics (for faster pub get)
        run: flutter config --no-analytics

      - name: Get Flutter packages
        run: flutter pub get

      - name: Run Flutter doctor
        run: flutter doctor -v

      - name: Build Android debug APK
        run: flutter build apk --debug --no-shrink
