name: Build PR

on:
  pull_request:

jobs:
  build-ios:
    runs-on: ubuntu-latest
    name: API Docker Image
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.29.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --simulator --no-codesign

  build-android:
    runs-on: ubuntu-latest
    name: API Docker Image
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.29.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android
        run: flutter build appbundle
